---
opa_old_versions:
  - 0.4
  - 0.5
opa_version: 0.7
k8s_config: |
  "exec-opts": ["native.cgroupdriver=systemd"],
  "icc": false,
  "live-restore": true,
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "10m",
    "max-file": "200"
  },
  "userland-proxy": false,
  "no-new-privileges": true,
  "experimental": true
