---
# runfile variables
cuda_url: http://developer.download.nvidia.com/compute/cuda/10.1/Prod/local_installers/cuda_10.1.243_418.87.00_linux.run
cuda_checksum: e7c22dc21278eb1b82f34a60ad7640b41ad3943d929bebda3008b72536855d31
cuda_verstr: 'CUDA Version 10.1.243'

# package variables
# keep these in sync with the runfile version so that cleanup stays reliable!
cuda_package_version: 10-1
cuda_path_version: 10.1
