fw_mq_str: 'Warning: ALREADY_ENABLED: masquerade'
git_reinit_str: 'Reinitialized existing Git repository'
git_uptodate_str: 'Everything up-to-date'

wg_port: 44444
wg_ip: 10.10.10.1
wg_clients: 5
wg_default_svc: /lib/firewalld/services/wireguard.xml
wg_users: 'john,jane,jules,juan,jose'
wg_tunnel: 'split'
