# make sure firewalld is installed, we need it for the reload
- include_role:
    name: firewalld

# we use /etc/firewalld, WG uses /lib/firewalld, causing a conflict, get rid of it
- name: Disable stock WireGuard firewall service
  file:
    path: "{{ wg_default_svc }}"
    state: absent
  register: wg_svc_delete

- name: Reload firewalld
  command:
    cmd: firewall-cmd --reload
  when: wg_svc_delete.changed

# this is for 'clients' reaching the 'server'
- include_role:
    name: firewalld
  vars:
  - service: 'wireguard'
  - port: "{{ wg_port }}/udp"

- name: Enable firewalld masquerade
  shell:
    cmd: firewall-cmd --add-masquerade --permanent && firewall-cmd --reload
  register: fw_mq
  changed_when: (fw_mq_str not in fw_mq.stderr)

# this is for 'clients' talking to each other
- include_role:
    name: firewalld
  vars:
  - zone: 'wireguard'
  - interface: 'wg0'
  - fw_target: 'ACCEPT'
