# a possible check for the existence of a service:
# firewall-cmd --get-services | grep -E '[[:space:]]{{ service }}[[:space:]]|^{{ service }}[[:space:]]|[[:space:]]{{ service }}$'
# that is, it's either ' http ' (MOL) or 'http ' (SOL) or ' http' (EOL)
# but it's probably simpler to just omit port number and be done with it

- name: "Create {{ service }} firewall service"
  shell: "firewall-cmd --permanent --new-service {{ service }} {% if zone is defined%}--zone={{ zone }}{% endif %} && firewall-cmd --reload"
  args:
    creates: "/etc/firewalld/services/{{ service }}.xml"
  when: port is defined

- name: "Add port {{ port }} to {{ service }} firewall service"
  shell: "firewall-cmd --permanent --service={{ service }} --add-port={{ port }} {% if zone is defined%}--zone={{ zone }}{% endif %} && firewall-cmd --reload"
  register: fw_port
  changed_when: ("ALREADY_ENABLED" not in fw_port.stderr)
  when: port is defined

- name: "Enable {{ service }} firewall service"
  shell: "firewall-cmd --permanent --add-service={{ service }} {% if zone is defined%}--zone={{ zone }}{% endif %} && firewall-cmd --reload"
  register: fw_svc
  changed_when: ("ALREADY_ENABLED" not in fw_svc.stderr)
